default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: app_golf_development

test:
  <<: *default
  database: app_golf_test

# production:
#   <<: *default
#   url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: app_golf_production
  username: julia-marietrudel
  host: localhost
  port: 5432
